research_task:
  description: >
    Conduct a thorough research about {topic}.
    Make sure you find any interesting and relevant non-financial information given
    the current year is {current_year}.
  expected_output: >
    A list of 5-10 bullet points summarizing the most relevant general information about '{topic}'.
    This output should focus on company overview, business activities, recent news (non-financial), etc.
  agent: researcher

financial_task: 
  description: >
    Given the company name '{company_name}', determine if it is a Korean company based on the 'is_korean' input ('{is_korean}').

    If '{is_korean}' is 'true' (meaning it's a Korean company):
    Collect its financial data for approximately the last two years (all available quarters within this period)
    using the 'Dart Financial Data Collector' tool. After collecting the data,
    perform a comprehensive time-series analysis of key financial metrics including 'revenue',
    'operating_income', 'net_income', 'asset_moveable' (유동자산), 'asset_unmoveable' (비유동자산),
    'bet_moveable' (유동부채), 'bet_unmoveable' (비유동부채), 'amount_asset' (자본총계), and 'amount_bet' (부채총계).
    
    Analyze trends, significant changes, and inter-relationships between these metrics over the entire two-year period.
    Based on this analysis, derive a **forward-looking financial outlook (전망)** for the company,
    identifying potential future performance and risks.
    
    The final output should be a structured JSON object containing:
    1. A summary of the financial data collected for each quarter.
    2. Key trends identified for each metric.
    3. Derived financial outlook/prospects with reasoning.
    4. Any identified risks or opportunities.

    If '{is_korean}' is 'false' (meaning it's NOT a Korean company):
    State clearly that the financial analysis is not applicable as the company is not Korean, and the 'CollectFinancialDataTool' tool is for Korean companies only. No financial data collection or analysis should be performed.
    The output should be a JSON object indicating the reason for non-applicability.
  expected_output: |
      A structured JSON object representing the comprehensive financial analysis.
      
      If it's a Korean company, the JSON should include:
      ```json
      {
        "company_name": "{company_name}",
        "financial_data_by_quarter": {
          "YYYY_Q1": { ... },
          "YYYY_Q2": { ... },
          "YYYY_Q3": { ... },
          "YYYY_Q4": { ... }
          // ... for approximately the last two years
        },
        "key_trends": {
          "revenue_trend": "...",
          "operating_income_trend": "...",
          "net_income_trend": "...",
          "asset_liability_structure_trend": "...",
          // ... other relevant trends
        },
        "financial_outlook": "...",
        "risks_and_opportunities": [
          "Risk 1",
          "Opportunity 1"
        ]
      }
      ```
      If it's NOT a Korean company, the JSON should be:
      ```json
      {
        "company_name": "{company_name}",
        "status": "Financial analysis not applicable",
        "reason": "This tool is exclusively for Korean companies."
      }
      ```
  agent: financial_analyst
  output_file: financial_analysis_{company_name}.json

reporting_task:
  description: >
    Review all the context you got from previous tasks and expand each piece of information (both general and financial)
    into a full section for a comprehensive report about '{topic}'.
    Make sure the report is detailed and contains any and all relevant information, including financial insights if applicable.
  expected_output: >
    A fully fledged, well-structured report about '{topic}' with main topics, 
    each with a full section of information, including financial analysis if available.
    Formatted as markdown without '```'
  agent: reporting_analyst
