research_task:
  description: >
    Conduct a thorough and comprehensive research on {topic}, focusing on the latest developments and market trends.
    Identify key breakthroughs, emerging technologies, significant industry shifts, and gather all relevant raw data for the current year {current_year}.
    Prioritize data that can be quantitatively analyzed for trends and patterns.
  expected_output: >
    A structured collection of raw research findings and relevant data points, ready for detailed analysis.
    This should include links to sources or clearly cited information, and any quantitative data should be in a parsable format (e.g., list of dictionaries or JSON-like structure).
  agent: researcher

data_analysis_task:
  description: >
    Perform in-depth statistical and quantitative analysis on the raw data and research findings provided by the Researcher.
    Identify significant trends, statistical correlations, growth rates, market shares, and any notable anomalies related to {topic} for the year {current_year}.
    Highlight key metrics and their evolution, and present the findings in a clear, analytical summary.
  expected_output: >
    A comprehensive analytical summary, including key quantitative insights, identified trends (e.g., growth rates, market shifts),
    and any statistically significant patterns or anomalies, presented in a structured text format suitable for report integration.
  agent: data_analyst
  context:
    - research_task

financial_analysis_task:
  description: >
    Perform a detailed financial analysis of {company_name} using the provided quarterly financial data.
    The analysis should cover three periods:
    1. Most recent quarter (A)
    2. Previous quarter (B)
    3. Same quarter one year ago (C)

    For each quarter, extract the following metrics:
    - Current Assets (유동 자산)
    - Non-current Assets (부동 자산)
    - Current Liabilities (유동 부채)
    - Non-current Liabilities (부동 부채)
    - Operating Profit (영업 이익)
    - Net Income (당기순 이익)

    Calculate the following financial ratios for each quarter:
    - Current Ratio (유동비율): Current Assets / Current Liabilities
    - Debt-to-Equity Ratio (부채비율): Total Liabilities / Shareholder Equity (You'll need to infer Shareholder Equity or assume it's provided, if not, adjust formula or input)
    - Quick Ratio (당좌비율): (Current Assets - Inventory) / Current Liabilities (Assume inventory is not provided and use a proxy or clarify in the prompt if needed, e.g., (Current Assets - Prepaid Expenses) / Current Liabilities)

    Finally, provide a comparative analysis:
    - Quarter-over-quarter comparison (A vs. B): Highlight changes in each metric and ratio, along with insights into the company's short-term performance.
    - Year-over-year comparison (A vs. C): Highlight changes in each metric and ratio, along with insights into long-term trends and seasonal effects.

    The input for this task should be raw financial data for each quarter.
  expected_output: >
    A structured financial analysis report including:
    - Tabular data for each quarter showing all extracted metrics and calculated ratios.
    - Clear summaries of quarter-over-quarter and year-over-year comparisons for each metric and ratio.
    - Concise insights derived from the comparative analysis, explaining the financial implications of the changes.
    The output should be ready for integration into a comprehensive report.
  agent: financial_analyst
  context:


strategy_development_task:
  description: >
    Based on the in-depth research findings, the quantitative data analysis, and the detailed financial analysis, develop actionable and forward-looking strategies and practical recommendations for {topic} and {company_name}.
    Consider the current market landscape, potential future implications, competitive advantages, and challenges, incorporating insights from the financial health of the company.
    Formulate specific, measurable, achievable, relevant, and time-bound (SMART) recommendations for stakeholders.
  expected_output: >
    A concise list of strategic recommendations, each clearly justified by the research, data analysis, and financial performance insights,
    along with their potential impact and practical steps for implementation, presented in a structured format.
  agent: strategist
  context:
    - research_task
    - data_analysis_task
    - financial_analysis_task

reporting_task:
  description: >
    Consolidate all findings from the Researcher, data analysis from the Data Analyst, financial analysis from the Financial Analyst, and strategic recommendations from the Strategist into a single, comprehensive, and well-structured report.
    The report must include an executive summary, detailed findings from research, in-depth data analysis insights, a dedicated section for financial analysis, and a dedicated section for strategic recommendations.
    Ensure the report is clear, concise, professional, and logically flows from problem identification to actionable solutions.
  expected_output: >
    A fully fledged, professional report in English, ready for presentation.
    The report should be formatted as markdown without '```' and include clear headings for each section (e.g., Executive Summary, Research Findings, Data Analysis, Financial Analysis, Strategic Recommendations).
  agent: reporting_analyst
  context:
    - research_task
    - data_analysis_task
    - financial_analysis_task
    - strategy_development_task

translation_task:
  description: >
    Translate the entire comprehensive report provided by the Reporting Analyst into natural, accurate, and contextually appropriate Korean.
    Ensure all sections, headings, sub-headings, and every detail are translated while maintaining the original meaning, nuance, and professional tone, especially for technical terms specific to {topic}.
    The translated report should be meticulously proofread and ready for immediate presentation to a Korean-speaking audience.
  expected_output: >
    A fully translated, polished report in Korean, formatted as markdown.
  agent: translator
  context:
    - reporting_task
