version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: crewai
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crewaiDemo
    volumes:
      - ./mongo_data_local:/data/db
    restart: always

volumes:
  mongo_data: