version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: crewai_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crewaiDemo
    volumes:
      - ./mongo_data_local:/data/db
    restart: always

  crewai_app:
    image: soldiersung/sbt_crewai:latest
    container_name: sbt_crewai
    ports:
      - "8009:8008"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo_data_local: # MongoDB 데이터 볼륨 정의
